### ISSUE TITLE
Dependability Competition

### ISSUE THREAD

**Issue by schuschu** [d3s-trento/crystal#1]
Hi,

I noticed that the following files are  missing: app-depcomp.c and app-depcomp.h 
The c file is included in app.c https://github.com/d3s-trento/crystal/blob/7384f4fefbc2c650c936544a2939a468df278317/apps/crystal/app.c#L2

The header is referenced here:
https://github.com/d3s-trento/crystal/blob/85bfea10489e2a54effcfd88aa397a6ec940ae09/apps/crystal/app.h#L4

**Comment by tim-ist** [comment]
I've pushed the code and the parameter set we used for the final competition binary to the `depcomp18` branch.
